export const SEVERITY = { LOW: 'LOW', MEDIUM: 'MEDIUM', HIGH: 'HIGH', CRITICAL: 'CRITICAL' }

export const MSG = {
  REGISTER: 'REGISTER',
  DEREGISTER: 'DEREGISTER',
  HEARTBEAT: 'HEARTBEAT',
  SERVICES: 'SERVICES',
  NEAREST: 'NEAREST',
  NEAREST_RESULT: 'NEAREST_RESULT',
  ALERT: 'ALERT',
  ALERT_DUPLICATE: 'ALERT_DUPLICATE',
  INCIDENT_MERGED: 'INCIDENT_MERGED',
  ALERT_CANCEL: 'ALERT_CANCEL',
  INCIDENT_NOTE: 'INCIDENT_NOTE',
  INCIDENT_CHAT: 'INCIDENT_CHAT',
  INCIDENT_PHOTO: 'INCIDENT_PHOTO',
  SAFETY_UPDATE: 'SAFETY_UPDATE',
  ALERT_ACK: 'ALERT_ACK',
  ALERT_ESCALATED: 'ALERT_ESCALATED',
  DISPATCH_UPDATE: 'DISPATCH_UPDATE',
  CHAT: 'CHAT',
  INCIDENT_UPDATE: 'INCIDENT_UPDATE',
  LOCATION_UPDATE: 'LOCATION_UPDATE',
  LOG: 'LOG',
  PING: 'PING',
  PONG: 'PONG',
}

export function pack(type, payload = {}) {
  return JSON.stringify({ type, payload, ts: Date.now() })
}

export function parse(raw) {
  try {
    return JSON.parse(raw)
  } catch {
    return null
  }
}